### ISSUE TITLE
flutter 升级到2.10.1之后TRTC不能用会报错

### ISSUE THREAD

**Issue by wyq09** [LiteAVSDK/TRTC_Flutter#36]
Execution failed for task ':tencent_trtc_cloud:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':tencent_trtc_cloud:debugCompileClasspath'.
   > Failed to transform LiteAVSDK_TRTC-9.5.11171.jar (com.tencent.liteav:LiteAVSDK_TRTC:9.5.11171) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find LiteAVSDK_TRTC-9.5.11171.jar (com.tencent.liteav:LiteAVSDK_TRTC:9.5.11171).
        Searched in the following locations:
            https://maven.aliyun.com/repository/jcenter/com/tencent/liteav/LiteAVSDK_TRTC/9.5.11171/LiteAVSDK_TRTC-9.5.11171.jar

**Comment by c1avie** [comment]
测试是用的模拟器吗，安卓不支持模拟器，要使用真机测试
