### ISSUE TITLE
【ios】-【版本2.2.0】iphone6 屏幕分享中断 sdk版本不符

### ISSUE THREAD

**Issue by ruolunhui** [LiteAVSDK/TRTC_Flutter#47]
【当前现象】：iphone6 系统版本 12.5.5 点击录屏直播，直接中断，提示屏幕分享已停止 sdk版本不符，晚点补图片

【SDKAppID】：1400644175
【房间号】: 1256732
【useID】：339473
【问题时间段】：2021-04-07 15:23~16:55
【机型】：iphone6
【之前版本有无此问题】：
【是否必现】：必现
【复现方法】：
【日志或者描述、截图】：

**Comment by c1avie** [comment]
是跑的TRTC-API-Example 这个demo吗

**Comment by c1avie** [comment]
是有这个问题，我们明天修改下哈

**Comment by ruolunhui** [comment]
好的，非常感谢

**Comment by c1avie** [comment]
修复了，重新拉下TRTC-API-Example的代码试试。
删除之前的pods文件，重新pod install一下
