### ISSUE TITLE
想问下ios端sdk能否监听用户是否同意录屏

### ISSUE THREAD

**Issue by ruolunhui** [LiteAVSDK/TRTC_Flutter#48]
您好 想问下ios端sdk能否监听用户是否同意录屏
在android端如果用户不同意录屏 能收到用户拒绝屏幕分享的回调 但是在ios 弹出屏幕分享页面之后 用户不点击开始屏幕分享 sdk没有回调用户拒绝录制 
是我这边处理的逻辑有问题 还是用户是否拒绝需要另外单独自行实现？

**Comment by c1avie** [comment]
这个没有 系统回调也没有
