### ISSUE TITLE
ios启动模拟器报错

### ISSUE THREAD

**Issue by WebDou** [LiteAVSDK/TRTC_Flutter#49]
ios/Pods/TXLiteAVSDK_Live/TXLiteAVSDK_Live/TXLiteAVSDK_Live.framework/TXLiteAVSDK_Live(TRTCClou
d.o), building for iOS Simulator, but linking in object file built for iOS, file
/ios/Pods/TXLiteAVSDK_Live/TXLiteAVSDK_Live/TXLiteAVSDK_Live.framework/TXLiteAVSDK_Live' for
architecture arm64

**Comment by c1avie** [comment]
https://www.jianshu.com/p/0fc2a6402870   可以看下这里的解决方案
