### ISSUE TITLE
如何获取本地音频流，实现语音识别展示字幕

### ISSUE THREAD

**Issue by WebDou** [LiteAVSDK/TRTC_Flutter#50]

**Comment by c1avie** [comment]
tencent_trtc_cloud_professional   你可以试着用这个插件，这个插件有实现本地音频流   setAudioFrameListener方法

**Comment by WebDou** [comment]
通过onCapturedRawAudioFrame获取到音频数据，如何转换成腾讯实时语音识别websocket要求的二进制语音数据。

**Comment by c1avie** [comment]
flutter这边返回的是Uint8List 格式的音频数据，可以问下 实时语音团队怎么去识别这个数据。
