### ISSUE TITLE
【ios】-【2.2.4】闪退

### ISSUE THREAD

**Issue by fangwy** [LiteAVSDK/TRTC_Flutter#51]
【当前现象】：闪退
【SDKAppID】：1400647623
【房间号】: 72800502
【useID】：1949
【问题时间段】：2022-06-14 16:07:26~16:07:26
【机型】：iPhone 8 Plus (A1864/A1898)(15.4)
【之前版本有无此问题】：不清楚
【是否必现】：偶现
【复现方法】：进房马上退出
【日志或者描述、截图】：

`tencent_trtc_cloud/TencentTRTCCloud.swift:317: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread # 1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000184fcbebc libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x184fcbebc <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x184fcbec0 <+0>: b      0x184fcbebc               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x184fcbec4 <+0>: adrp   x8, 463957
    0x184fcbec8 <+4>: ldrb   w0, [x8, #0x60c]
Target 0: (Runner) stopped.
Lost connection to device.`

**Comment by c1avie** [comment]
跑哪个demo出现的？

**Comment by fangwy** [comment]
> 跑哪个demo出现的？

非demo实际项目做通话时出现的

**Comment by c1avie** [comment]
先不要调用destroySharedInstance试试看

**Comment by c1avie** [comment]
好的，这里可能是调用时机不对导致的，sdk我抽空优化下

**Comment by 891806797** [comment]
我TRTC 2.3.4也是8P闪退，安卓没问题，老哥快解决一下吧

**Comment by c1avie** [comment]
调用时机这里，sdk已经优化，可以使用最新版本
