### ISSUE TITLE
【ios】-【2.3.0】编译运行失败：file cannot be found

### ISSUE THREAD

**Issue by devlei** [LiteAVSDK/TRTC_Flutter#52]
【当前现象】：编译失败
【SDKAppID】：xxxx
【房间号】: xxxx
【useID】：xxxx
【问题时间段】：2022-06-30 21:29
【机型】：iPhone 13 Pro，macOs 14 beta，M1 
【之前版本有无此问题】：没用之前版本
【是否必现】：必现
【复现方法】：下载SDK后，打开TRTC-Simple-Demo后，编译
【日志或者描述、截图】：
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/8512362/176691172-9c572724-e9e4-47cb-b889-e32b21e64538.png">
[log_build.md](https://github.com/LiteAVSDK/TRTC_Flutter/files/9020235/log_build.md)

**Comment by c1avie** [comment]
https://stackoverflow.com/questions/63948739/flutter-could-not-build-the-precompiled-application-for-the-device-error-laun。   看下这个
