### ISSUE TITLE
【iOS】TRTCCloudListener.onUserVoiceVolume事件的userId为空

### ISSUE THREAD

**Issue by chainzhang** [LiteAVSDK/TRTC_Flutter#57]
【当前现象】：获取的TRTCCloudListener.onUserVoiceVolume事件的userId为空，如下

```
{userId: , volume: 0}
```

Android没有该问题。
【版本】tencent_trtc_cloud: ^2.3.5
【SDK版本】：10.3.0.12231
【SDKAppID】：20000909
【房间号】:477df_ch_ZzNqSzQ5OTQzMjU2MTA0OTY@76207361
【useID】：477df_u76207300
【问题时间段】：NA
【机型】：iPhone7
【之前版本有无此问题】：未知
【是否必现】：必现 
【复现方法】：（demo还没有看，稍后补上。但现项目中iOS出现该问题）
【日志或者描述、截图】：

**Comment by c1avie** [comment]
userId为空表示自己

**Comment by chainzhang** [comment]
> userId为空表示自己

@c1avie 谢谢回复，请问Android也是一样的还是只有iOS是这个式样？

**Comment by c1avie** [comment]
安卓会返回自己的id
