### ISSUE TITLE
桌面端无法显示视频

### ISSUE THREAD

**Issue by yhz199132** [LiteAVSDK/TRTC_Flutter#63]
目前桌面端(windows/mac)无法显示视频，是目前版本不支持吗？  是否有相关开发计划？

**Comment by c1avie** [comment]
桌面端通过这种方式渲染
https://github.com/LiteAVSDK/TRTC_Flutter/blob/master/TRTC-API-Example/lib/Advanced/TextureRendering/VideoCallingPage.dart

**Comment by yhz199132** [comment]
非常感谢，问题解决，关闭问题
